[package]
name = "rusteam"
version = "0.4.1"
description = "Manage your games on the terminal"
authors = ["Oleksii Filonenko <brightone@protonmail.com>"]
homepage = "https://github.com/filalex77/rusteam"
repository = "https://github.com/filalex77/rusteam"
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
colored = "1.8"
directories = "2.0.2"
snafu = "0.4"
structopt = "0.2"
toml = "0.5"

[dependencies.serde]
version = "1.0"
features = ["derive"]
[dev-dependencies]
version-sync = "0.8.1"
