[package]
authors = ["Oleksii Filonenko <brightone@protonmail.com>"]
name = "rusteam"
description = "Manage your games on the terminal"
version = "0.3.0"
edition = "2018"
license = "GPL-3"
homepage = "https://github.com/filalex77/rusteam"
repository = "https://github.com/filalex77/rusteam"

[dependencies]
structopt = "0.2"
dirs = "2.0.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.1"
snafu = "0.4.3"
colored = "1.8.0"
