version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout

      - run:
          name: Version information
          command: |
            rustc --version
            cargo --version
            rustup --version

      - restore_cache:
          keys:
            - v1-target-{{ checksum "Cargo.lock" }}
            - v1-target-

      - run:
          name: Format
          command: |
            rustup component add rustfmt
            cargo fmt -- --check

      - run:
          name: Clippy
          command: |
            rustup component add clippy
            cargo clippy --all

      - run:
          name: Test
          command: "RUST_BACKTRACE=1 cargo test"

      - save_cache:
          key: v1-target-{{ checksum "Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"

workflows:
  version: 2.1
  build:
    jobs:
      - build
